# Generated by Django 3.2.7 on 2021-09-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='Email',
        ),
    ]
