# Generated by Django 3.2.7 on 2021-09-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_name_owner_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='Email',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
