# Generated by Django 3.2.7 on 2021-09-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210903_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumnail1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='thumnail2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
