# Generated by Django 3.2.7 on 2021-09-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210903_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='phone1',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='phone2',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
