# Generated by Django 3.2.7 on 2021-09-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210904_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='slug',
        ),
    ]
