# Generated by Django 3.2.7 on 2021-09-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
