# Generated by Django 3.2.7 on 2021-09-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_product_orderitem_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
