# Generated by Django 3.2.7 on 2021-09-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_product_id_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
