# Generated by Django 3.2.7 on 2021-09-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_orderitem_product_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='phone2',
        ),
    ]
